# 第二次课作业

（1）创建一个1到10的数组，然后逆序输出。

In [8]:
import numpy as np
a = np.arange(1,11)
a[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

（2）创建一个长度为20的全1数组，然后变成一个4×5的二维矩阵并转置。

In [14]:
a = np.ones(20,dtype=int)
a.reshape(4,5).T

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

（3）创建一个3x3x3的随机数组。
(提示: np.random.random)

In [17]:
np.random.random(27).reshape(3,3,3)

array([[[0.10370128, 0.77492751, 0.68773545],
        [0.49640358, 0.69096811, 0.29618125],
        [0.64726208, 0.36121832, 0.71767173]],

       [[0.91930692, 0.3299059 , 0.05610009],
        [0.82984827, 0.21013392, 0.34358901],
        [0.48348287, 0.02668445, 0.47891679]],

       [[0.61541042, 0.42860374, 0.49594973],
        [0.67411334, 0.4340803 , 0.39556953],
        [0.51544097, 0.19510581, 0.35005973]]])

（4）从1到10中随机选取10个数，构成一个长度为10的数组，并将其排序。获取其最大值最小值，求和，求方差。

In [23]:
a = np.random.randint(1,10,10)
sorted(a)

[1, 2, 4, 6, 6, 6, 7, 8, 8, 8]

In [25]:
print(np.max(a),np.min(a),np.sum(a),np.std(a))

8 1 56 2.3748684174075834


（5）从1到10中随机选取10个数，构成一个长度为10的数组，选出其中的奇数。

In [27]:
a = np.random.randint(1,10,10)
a

array([9, 6, 7, 8, 9, 2, 9, 1, 8, 6])

In [33]:
mask = np.array(a,dtype=bool)
mask[a%2==0]=0
a[mask]

array([9, 7, 9, 9, 1])

（6）生成0到100，差为5的一个等差数列，然后将数据类型转化为整数。

In [37]:
 np.linspace(0,100,21,dtype=int)

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100])

（7）从1到10中随机选取10个数，大于3和小于8的取负数。

In [47]:
a = np.random.randint(1,10,10)
b = np.where((a>3)&(a<8),-a,a)
b

array([ 2,  1,  8,  1,  3, -4, -7,  9, -6,  1])

（8）在数组[1, 2, 3, 4, 5]中相邻两个数字中间插入1个0。

In [50]:
a = [1, 2, 3, 4, 5]
indx = (1,2,3,4)
np.insert(a,indx,0)

array([1, 0, 2, 0, 3, 0, 4, 0, 5])

（9）新建一个5乘5的随机二位数组，交换其中两行？比如交换第一二行。

In [61]:
a = np.random.random((5,5))
a

array([[0.52547527, 0.61102844, 0.11522208, 0.02217672, 0.69027212],
       [0.60251602, 0.56891773, 0.76920984, 0.97663689, 0.1031417 ],
       [0.74453387, 0.15591182, 0.34475844, 0.10468559, 0.97149781],
       [0.2207815 , 0.66259792, 0.63829592, 0.45858265, 0.61885847],
       [0.25756824, 0.64711738, 0.2977207 , 0.37885618, 0.95502558]])

In [62]:
a[[0,1]]=a[[1,0]]
a

array([[0.60251602, 0.56891773, 0.76920984, 0.97663689, 0.1031417 ],
       [0.52547527, 0.61102844, 0.11522208, 0.02217672, 0.69027212],
       [0.74453387, 0.15591182, 0.34475844, 0.10468559, 0.97149781],
       [0.2207815 , 0.66259792, 0.63829592, 0.45858265, 0.61885847],
       [0.25756824, 0.64711738, 0.2977207 , 0.37885618, 0.95502558]])

（10）把一个10\*2的随机生成的笛卡尔坐标转换成极坐标。

（11）创建一个长度为10并且除了第五个值为1其余的值为2的向量。

In [65]:
mask = np.array([0,0,0,0,1,0,0,0,0,0])
np.where(mask==1,1,2)

array([2, 2, 2, 2, 1, 2, 2, 2, 2, 2])

（12）创建一个长度为10的随机向量，并求其累计和。

In [67]:
a = np.random.random(10)
print(a,sum(a))

[0.45884097 0.86411218 0.82433152 0.74471049 0.55164288 0.25805658
 0.56472437 0.78378047 0.70665816 0.54089881] 6.297756423822302


（13）将数组中的所有奇数替换成-1。

In [71]:
a = np.random.randint(1,100,20)
b = np.where(a%2==1,-1,a)
b

array([50, -1, 82, -1, 92, 74, -1, -1, -1, 78, 80, 26, 14, 64, -1, 10, -1,
       -1, -1, -1])

（14）构造两个4乘3的二维数组，按照3种方法进行连接？

In [74]:
a = np.array([[1,2,3],[11,12,13],[21,22,23],[31,32,33]])
b = np.array([[7,8,9],[77,78,79],[87,88,89],[97,98,99]])
z1 = np.concatenate((a,b))
z1   

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33],
       [ 7,  8,  9],
       [77, 78, 79],
       [87, 88, 89],
       [97, 98, 99]])

In [76]:
z2 = np.concatenate((a,b),axis=1)
z2

array([[ 1,  2,  3,  7,  8,  9],
       [11, 12, 13, 77, 78, 79],
       [21, 22, 23, 87, 88, 89],
       [31, 32, 33, 97, 98, 99]])

In [78]:
z3 = np.array((a,b))
z3

array([[[ 1,  2,  3],
        [11, 12, 13],
        [21, 22, 23],
        [31, 32, 33]],

       [[ 7,  8,  9],
        [77, 78, 79],
        [87, 88, 89],
        [97, 98, 99]]])

In [83]:
print(np.vstack((a,b)),np.hstack((a,b)),np.dstack((a,b)))

[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]
 [ 7  8  9]
 [77 78 79]
 [87 88 89]
 [97 98 99]] [[ 1  2  3  7  8  9]
 [11 12 13 77 78 79]
 [21 22 23 87 88 89]
 [31 32 33 97 98 99]] [[[ 1  7]
  [ 2  8]
  [ 3  9]]

 [[11 77]
  [12 78]
  [13 79]]

 [[21 87]
  [22 88]
  [23 89]]

 [[31 97]
  [32 98]
  [33 99]]]


（15）获取数组 a 和 b 中的共同项（索引位置相同，值也相同）。
a = np.array([1,2,3,2,3,4,3,4,5,6])，b = np.array([7,2,10,2,7,4,9,4,9,8])

In [85]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
z = np.where(a==b)
a[z]

array([2, 2, 4, 4])

（16）从数组 a 中提取 5 和 10 之间的所有项。a=np.array([7,2,10,2,7,4,9,4,9,8])

In [86]:
a=np.array([7,2,10,2,7,4,9,4,9,8])
a[np.where((a>5)&(a<10))]

array([7, 7, 9, 9, 8])